##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## task01 Day10
##

SRC	=	count_words.c

OBJ	=	$(SRC:.c=.o)

NAME 	= 	countwords

all:		$(SRC)
		gcc -o $(NAME) $(SRC)

clean:	
		rm -f $(NAME)

fclean: 	clean
		rm -f $(NAME)

re:		fclean all	
