#!/usr/bin/env python3
#-*- coding: utf-8 -*-

import sys
import operations

def main():
    if int(sys.argv[1]) == 1:
        operations.do_sphere(sys.argv)
    elif int(sys.argv[1]) == 2:
        operations.do_cylinder(sys.argv)
    elif int(sys.argv[1]) == 3:
        operations.do_cone(sys.argv)

main()
