##
## EPITECH PROJECT, 2017
## Makefile
## File description:
## task01 Day10
##

SRC	=	main.c	\

OBJ	=	$(SRC:.c=.o)

NAME 	= 	palindrome

all:		$(SRC)
		gcc -o $(NAME) $(SRC) -g

clean:	
		rm -f $(NAME)

fclean: 	clean
		rm -f $(NAME)

re:		fclean all	
