##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile
##

NAME1 = challenge01
NAME2 = challenge02
NAME3 = challenge03
NAME4 = challenge04
NAME5 = challenge05
NAME6 = challenge06
NAME7 = challenge07

all:
	cp challenge01.py $(NAME1)
	cp challenge02.py $(NAME2)
	cp challenge03.py $(NAME3)
	cp challenge04.py $(NAME4)
	cp challenge05.py $(NAME5)
	cp challenge06.py $(NAME6)
	cp challenge07.py $(NAME7)
	chmod 755 $(NAME1)
	chmod 755 $(NAME2)
	chmod 755 $(NAME3)
	chmod 755 $(NAME4)
	chmod 755 $(NAME5)
	chmod 755 $(NAME6)
	chmod 755 $(NAME7)

clean:
	rm $(NAME1)
	rm $(NAME2)
	rm $(NAME3)
	rm $(NAME4)
	rm $(NAME5)
	rm $(NAME6)
	rm $(NAME7)

fclean: clean

re:	fclean all

.PHONY:			re fclean clean
